[tool.poetry]
name = "ntcu-machine-learning"
version = "0.1.0"
description = ""
authors = ["alan0983 <95973687+alan0983@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.3.1"
pandas = "^2.3.0"
scikit-learn = "^1.7.0"
kagglehub = "^0.3.12"
xgboost = "^3.0.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
